api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    
    title: 'Api SoccerApp'
    version: '0.0.1'

    formats:
        json:
            mime_types: ['application/json']

        jsonld:
            mime_types: ['application/ld+json']

        html:
            mime_types: ['text/html']
